article/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "article"
urlpatterns = [
    path('', views.articles, name="articles"),
    path('addarticle/', views.addarticle, name="addarticle"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.updateArticle, name="update"),
    path('delete/<int:id>', views.deleteArticle, name="delete"),
    path('comment/<int:id>', views.addComment, name="addComment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/', views.about,name="about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "user"
 
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
]

article/models.py
from ckeditor.fields import RichTextField
from django.db import models

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True)
    article_image = models.FileField(blank=True, null=True, verbose_name="Add an image for your article:")
    def __str__(self):
        return self.title
    class Meta:
        ordering =['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="Article", related_name="comments")
    comment_author = models.CharField(max_length=50, verbose_name="Author")
    comment_content = models.CharField(max_length=200, verbose_name="Comment")
    commment_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering =['-commment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "article_image"]

user/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50, label = "Username")
    password = forms.CharField(max_length=20, label = "Password", widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20, label = "Confirm", widget = forms.PasswordInput)
    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")
        if password and confirm and password != confirm:
            raise forms.ValidationError("Passwords do not match...")
        values = {
            "username" : username,
            "password" : password
        }
        return values

class LoginForm(forms.Form):
    username = forms.CharField(label = "Username")
    password = forms.CharField(label = "Password", widget=forms.PasswordInput)

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404,reverse
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm
from django.contrib import messages
from.models import Article, Comment

def index(request):
    return render(request, "index.html")

def about(request):
    return render(request, "about.html")

def articles(request):
    keyword = request.GET.get("sw")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles":articles})
    articles =  Article.objects.all()
    return render(request, "articles.html", {"articles":articles,})

@login_required(login_url="user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, 'Article added successfully!')
        return redirect("index")
    return render(request, "addarticle.html",{"form":form})

@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    return render(request, "dashboard.html",{"articles":articles,})

def detail(request, id):
    article = get_object_or_404(Article, id = id)
    comments = article.comments.all
    return render(request, "details.html", {"article":article,"comments":comments,})

@login_required(login_url="user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article, id = id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, 'Article updated successfully!')
        return redirect("index")
    return render(request, "update.html",{"form":form,})

@login_required(login_url="user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()
    messages.success(request, 'Article deleted successfully!')
    return redirect("article:dashboard")

def addComment(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method =="POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        newComment = Comment(comment_author=comment_author, comment_content=comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id,}))

user/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages


# Create your views here.

def register(request):
    form = RegisterForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            newUser = User(username=username)
            newUser.set_password(password)
            newUser.save()
            login(request, newUser)
            messages.success(request, 'Register successfull!')
            return redirect("index")
    context = {
        "form" : form,
    }
    return render(request, "register.html", context)

def loginUser(request):
    form  = LoginForm(request.POST or None)
    context = {
        "form" : form,
    }
    if request.method == "POST" and form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username = username, password = password)
        if user is None:
            messages.info(request, "No such user...")
            return render(request, "login.html", context)
        messages.success(request, "Login successfull.")
        login(request, user)
        return redirect("index")
    return render(request, "login.html", context)

def logoutUser(request):
    logout(request)
    messages.success(request, "Logout successfull.")
    return redirect("index")

templates/about.html
{% extends 'layout.html' %}
{% block body %}
    <h3>About us...</h3>
    <hr>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
        Quisque urna ligula, vestibulum at sem et, feugiat faucibus 
        augue. Vivamus pulvinar bibendum metus placerat fringilla. 
        Vivamus pulvinar, diam at dictum aliquam, dolor diam hendrerit 
        tortor, eu feugiat turpis tellus non nisi. Vestibulum eu orci
        libero. Pellentesque pretium condimentum eros. Aenean vel nunc
        et orci aliquam ullamcorper a quis arcu. Proin sit amet tellus
        id ligula mattis egestas. Mauris velit eros, mollis ut euismod
        vel, cursus non lectus. Cras hendrerit iaculis sem, in l
        obortis nunc cursus at. Mauris vel finibus est. Quisque ipsum
        ligula, rutrum vel mauris vel, dictum congue sem. Integer.
    </p>
    <hr>
{% endblock body %}

templates/addarticle.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3"> 
        <h3>Add Article</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/articles.html
{% extends 'layout.html' %}

{% block body %}
<div class="row">
    <div class="col-lg-8">
        <h3>Makaleler</h3>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-lg-8">
        <form>
            {% csrf_token %}
            <input type="text" class="input" maxlength="64" placeholder="Search..." name="sw">
            <button type="submit" class="btn btn-primary btn-sm">Search</button>
        </form>
</div>
</div>
{% if articles %}
<div class="row">
    {% for article in articles %}
            <!-- Post Content Column -->
            <div class="col-lg-8">
                <!-- Title -->
                <a href="{% url 'article:detail' article.id %}"><h3 class="mt-4">{{article.title}}</h3></a>
                <!-- Author -->
                <p class="lead">by {{article.author.username}}</p>
                <hr>
                <!-- Date/Time -->
                <p>Posted on: {{article.created_date}}</p>
                {% if article.article_image %}
                    <!-- Preview Image -->
                    <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
                {% endif %}
                <hr>
                <!-- Post Content -->
                <p >{{article.content|safe|truncatewords:70}}</p>
                <a href="{% url 'article:detail' article.id %}">Devamını oku...</a>
            </div>
    {% endfor %}
</div>
{% else %}
<div class="row">
    <div class="col-lg-8">
        <div class="alert alert-danger">No articles found...</div>
</div>
</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends 'layout.html' %}
{% block body %}
<h3>Dashboard</h3>
<hr>
<small>Welcome, {{request.user.username}}!</small>
<hr>
<a href="{% url 'article:addarticle' %}" class="btn btn-primary">Add Article...</a>
<br><br>
{% if articles %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Created Date</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
{% for article in articles %}
    <tbody>
        <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class="btn btn-danger">Update</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Delete</a></td>
        </tr>
    </tbody>
{% endfor %}
</table>
{% else %}
<hr>
<div class="alert alert-warning"> No articles found.</div>
{% endif %}
{% endblock body %}

templates/details.html
{% extends 'layout.html' %}

{% block body %}

<div class="row">
      <!-- Post Content Column -->
      <div class="col-lg-8">
            <!-- Title -->
            <h3 class="mt-4">{{article.title}}</h3>
            <!-- Author -->
            <p class="lead">by {{article.author.username}}</p>
            <hr>
            <!-- Date/Time -->
            <p>Posted on: {{article.created_date}}</p>
            {% if article.article_image %}
                  <!-- Preview Image -->
                  <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
            {% endif %}
            <hr>
            <!-- Post Content -->
            <p >{{article.content|safe}}</p>
            <!-- Add Comment -->
            <div class="card my-4">
                  <h5 class="card-header">Leave a Comment:</h5>
                  <div class="card-body">
                        <form  method="POST" action="{% url 'article:addComment' article.id %}">
                              {% csrf_token %}
                              <div class="form-group">
                                    <label for="name">Name:</label>
                                    <input name="comment_author" class="form-control" >
                                    </div>
                              <div class="form-group">
                                    <label for="comment">Comment:</label>
                                    <textarea name="comment_content" class="form-control" rows="3"></textarea>
                              </div>
                              <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                  </div>
            </div>
            {% if comments %}
            <!-- Single Comment -->
                  {% for comment in comments %}
                        <div class="media mb-4">
                              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                              <div class="media-body">
                                    <h5 class="mt-0">{{comment.comment_author}}</h5>
                                     <p>{{comment.comment_content}}</p>
                              </div>
                        </div>
                  {% endfor %}
            {% else %}
                  <div class="alert alert-danger">No comments for this post...</div>
            {% endif %}
        </div>
</div>
{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">YB Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active"><a class="nav-link" href="{% url 'about' %}">About</span></a></li>
        <li class="nav-item active"><a class="nav-link" href="{% url 'article:articles' %}">Articles</span></a></li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
            <li class="nav-item active"><a class="nav-link" href="{% url 'article:dashboard' %}">Dashboard</span></a></li>
            <li class="nav-item active"><a class="nav-link" href="{% url 'user:logout' %}">Logout</span></a></li>
        {% else %}
            <li class="nav-item active"><a class="nav-link" href="{% url 'user:login' %}">Login</span></a></li>
            <li class="nav-item active"><a class="nav-link" href="{% url 'user:register' %}">Register</span></a></li>
        {% endif %}
    </ul>
    </div>
</nav>

templates/index.html
{% extends 'layout.html' %}
{% block body %}
    <div class="jumbotron text-center">
        <h3>Lorem ipsum dolor sit amet.</h3>
        <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            Quasi harum beatae eius rem, voluptatem necessitatibus!
        </p>
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>YB Blog</title>
</head>
<body>
    {% include "includes/navbar.html" %}   
    <div class="container" style="margin-top:100px; margin-bottom: 150px;">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "info" %}
                    <div class="alert messages alert-danger">{{ message }}</div>
                {% else %}
                    <div class="alert messages alert-{{ message.tags }}">{{ message }}</div>
                {% endif %}
            {% endfor %}
         {% endif %}
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    <script>
        window.Tether = {};
      </script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/login.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3"> 
        <h3>Login</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3"> 
        <h3>Register</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

templates/update.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3"> 
        <h3>Update Article</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock body %}